# PUT THIS FILE IN A SPERATE FOLDER AND MOVE ALL THE YOUTUBE-LEARNING-MODE SERVICES INTO THAT FOLDER
# FOR IT TO WORK


version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  main-backend:
    build:
      context: ./Youtube-Learning-Mode/backend
    container_name: main-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  youtube-info-service:
    build:
      context: ./Youtube-Learning-Mode-Info-Service
    container_name: youtube-info-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  ai-service:
    build:
      context: ./Youtube-Learning-Mode-Ai-Service
    container_name: ai-service
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - app-network

  video-processing-service:
    build:
      context: ./Youtube-Learning-Mode-Video-Processing-Service
    container_name: video-processing-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
